import {
  Phone,
  ArrowRight,
  ArrowUp,
  Check,
  CircleX,
  TriangleAlert,
  PenLine,
  Image,
  CalendarOff,
  UserPlus,
  Clock,
  UtensilsCrossed,
  Hammer,
  Scissors,
  Scale,
  Gauge,
  MapPin,
  Banknote,
  Camera,
  FileText,
  Globe,
  Map,
  Bell,
  Smartphone,
  Star,
  TrendingDown,
  Calculator,
  Mail,
  Building2,
  Users,
  Receipt,
  Ban,
  ListChecks,
  CalendarDays,
  MessageCircle,
  Handshake,
  Link2,
  Repeat2,
  CodeXml,
  CircleDollarSign,
  Target,
  Zap,
  Percent,
  HandCoins,
  Menu,
  Key,
  Route,
  CircleHelp,
  ScrollText,
  Shield,
  Landmark,
  type LucideIcon,
} from 'lucide-react';

/** 使うアイコンだけを明示的に参照。静的ビルド時に SVG へ変換する。 */
export const ICONS = {
  phone: Phone,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  check: Check,
  'circle-x': CircleX,
  'triangle-alert': TriangleAlert,
  'pen-line': PenLine,
  image: Image,
  'calendar-off': CalendarOff,
  'user-plus': UserPlus,
  clock: Clock,
  'utensils-crossed': UtensilsCrossed,
  hammer: Hammer,
  scissors: Scissors,
  scale: Scale,
  gauge: Gauge,
  'map-pin': MapPin,
  banknote: Banknote,
  camera: Camera,
  'file-text': FileText,
  globe: Globe,
  map: Map,
  bell: Bell,
  smartphone: Smartphone,
  star: Star,
  'trending-down': TrendingDown,
  calculator: Calculator,
  mail: Mail,
  'building-2': Building2,
  users: Users,
  receipt: Receipt,
  ban: Ban,
  'list-checks': ListChecks,
  'calendar-days': CalendarDays,
  'message-circle': MessageCircle,
  handshake: Handshake,
  'link-2': Link2,
  'repeat-2': Repeat2,
  'code-xml': CodeXml,
  'circle-dollar-sign': CircleDollarSign,
  target: Target,
  zap: Zap,
  percent: Percent,
  'hand-coins': HandCoins,
  menu: Menu,
  key: Key,
  route: Route,
  'circle-help': CircleHelp,
  'scroll-text': ScrollText,
  shield: Shield,
  landmark: Landmark,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
