import {
  Phone,
  ArrowRight,
  ArrowUp,
  ChevronDown,
  Check,
  X,
  CircleCheck,
  CircleX,
  Info,
  TriangleAlert,
  PenLine,
  Image,
  CalendarOff,
  UserPlus,
  Clock,
  UtensilsCrossed,
  Hammer,
  Scissors,
  Scale,
  Gauge,
  MapPin,
  Banknote,
  Camera,
  FileText,
  Globe,
  Map,
  Bell,
  Smartphone,
  ShieldCheck,
  Star,
  Search,
  GitBranch,
  LockOpen,
  TrendingDown,
  Calculator,
  Mail,
  Building2,
  Users,
  Coins,
  Receipt,
  Ban,
  Eye,
  ListChecks,
  CalendarDays,
  MessageCircle,
  Handshake,
  Sparkles,
  Link2,
  WalletMinimal,
  Repeat2,
  CodeXml,
  CircleDollarSign,
  Target,
  Zap,
  ThumbsDown,
  Percent,
  HandCoins,
  Menu,
  Key,
  House,
  Route,
  CircleHelp,
  ScrollText,
  Shield,
  Landmark,
  MoveRight,
  type LucideIcon,
} from 'lucide-react';

/** 使うアイコンだけを明示的に参照。静的ビルド時に SVG へ変換する。 */
export const ICONS = {
  phone: Phone,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'chevron-down': ChevronDown,
  check: Check,
  x: X,
  'circle-check': CircleCheck,
  'circle-x': CircleX,
  info: Info,
  'triangle-alert': TriangleAlert,
  'pen-line': PenLine,
  image: Image,
  'calendar-off': CalendarOff,
  'user-plus': UserPlus,
  clock: Clock,
  'utensils-crossed': UtensilsCrossed,
  hammer: Hammer,
  scissors: Scissors,
  scale: Scale,
  gauge: Gauge,
  'map-pin': MapPin,
  banknote: Banknote,
  camera: Camera,
  'file-text': FileText,
  globe: Globe,
  map: Map,
  bell: Bell,
  smartphone: Smartphone,
  'shield-check': ShieldCheck,
  star: Star,
  search: Search,
  'git-branch': GitBranch,
  'lock-open': LockOpen,
  'trending-down': TrendingDown,
  calculator: Calculator,
  mail: Mail,
  'building-2': Building2,
  users: Users,
  coins: Coins,
  receipt: Receipt,
  ban: Ban,
  eye: Eye,
  'list-checks': ListChecks,
  'calendar-days': CalendarDays,
  'message-circle': MessageCircle,
  handshake: Handshake,
  sparkles: Sparkles,
  'link-2': Link2,
  'wallet-minimal': WalletMinimal,
  'repeat-2': Repeat2,
  'code-xml': CodeXml,
  'circle-dollar-sign': CircleDollarSign,
  target: Target,
  zap: Zap,
  'thumbs-down': ThumbsDown,
  percent: Percent,
  'hand-coins': HandCoins,
  menu: Menu,
  key: Key,
  house: House,
  route: Route,
  'circle-help': CircleHelp,
  'scroll-text': ScrollText,
  shield: Shield,
  landmark: Landmark,
  'move-right': MoveRight,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
