version: 2
updates:
  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      next-react:
        patterns: [next, react, react-dom, '@types/react*', eslint-config-next]
      development:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
